const BASE_SERVER_URL = "http://localhost:4000";

const API_TO_FETCH_COLLEGE_INFO = BASE_SERVER_URL + "/fetchCollegeList";

const API_TO_SIGNUP_USER = BASE_SERVER_URL + "/signupUser";

const API_TO_LOGIN_USER = BASE_SERVER_URL + "/login";

const API_TO_VERIFY_REFRESH_TOKEN = BASE_SERVER_URL + "/refresh";

const API_TO_RESET_PASSWORD = BASE_SERVER_URL + "/resetPassword";

const API_TO_UPDATE_PASSWORD = BASE_SERVER_URL + "/updatePassword";

const API_TO_SAVE_POST = BASE_SERVER_URL + "/savePost";

const API_TO_FETCH_ALL_POSTS = "/allPosts";

export {
  API_TO_FETCH_COLLEGE_INFO,
  API_TO_SIGNUP_USER,
  API_TO_LOGIN_USER,
  API_TO_VERIFY_REFRESH_TOKEN,
  API_TO_RESET_PASSWORD,
  API_TO_UPDATE_PASSWORD,
  API_TO_SAVE_POST,
  API_TO_FETCH_ALL_POSTS
};
