const BASE_SERVER_URL = "http://localhost:4000";

const API_TO_FETCH_COLLEGE_INFO = BASE_SERVER_URL + "/fetchCollegeList";

const API_TO_SIGNUP_USER = BASE_SERVER_URL + "/signupUser";

const API_TO_LOGIN_USER = BASE_SERVER_URL + "/login";

const API_TO_VERIFY_REFRESH_TOKEN = BASE_SERVER_URL + "/refresh";

const API_TO_RESET_PASSWORD = BASE_SERVER_URL + "/resetPassword";

const API_TO_UPDATE_PASSWORD = BASE_SERVER_URL + "/updatePassword";

const API_TO_SAVE_POST = BASE_SERVER_URL + "/savePost";

const API_TO_FETCH_ALL_POSTS = BASE_SERVER_URL + "/allPosts";

const API_TO_SEARCH_USERS = BASE_SERVER_URL + "/searchUser";

const API_TO_FETCH_PROFILE_DETAILS = BASE_SERVER_URL + "/profileDetails";

const API_TO_FETCH_USER_DETAILS = BASE_SERVER_URL + "/userDetails";

const API_TO_EDIT_PROFILE_PHOTO = BASE_SERVER_URL + "/editProfilePhoto";
const API_TO_EDIT_PROFILE = BASE_SERVER_URL + "/editProfile";

const API_TO_FETCH_POST_DETAILS = BASE_SERVER_URL + "/postDetails";

const API_TO_REPORT_POST = BASE_SERVER_URL + "/reportPost";
const API_TO_FETCH_POST_REPORTS = BASE_SERVER_URL + "/fetchPostReports";
const API_TO_APPROVE_POST_REPORTS = BASE_SERVER_URL + "/approvePostReports";
const API_TO_REJECT_POST_REPORTS = BASE_SERVER_URL + "/rejectPostReports";

const API_TO_FETCH_NOTIFICATIONS = BASE_SERVER_URL + "/fetchNotifications";

const API_TO_SAVE_COMMENTS = BASE_SERVER_URL + "/saveComments";

const API_TO_LIKE_UNLIKE_POST = BASE_SERVER_URL + "/like";

const API_TO_FETCH_POST_LIKES = BASE_SERVER_URL + "/fetchPostLikes";

const API_TO_DELETE_COMMENT = BASE_SERVER_URL + "/deleteComment";

const API_TO_DELETE_POST = BASE_SERVER_URL + "/deletePost";

const API_TO_FOLLOW_USER = BASE_SERVER_URL + "/follow";
const API_TO_UNFOLLOW_USER = BASE_SERVER_URL + "/unfollow";

const API_TO_FETCH_FOLLOWING_USERS = BASE_SERVER_URL + "/followingUsers";
const API_TO_FETCH_FOLLOWERS = BASE_SERVER_URL + "/followers";

export {
  API_TO_FETCH_COLLEGE_INFO,
  API_TO_SIGNUP_USER,
  API_TO_LOGIN_USER,
  API_TO_VERIFY_REFRESH_TOKEN,
  API_TO_RESET_PASSWORD,
  API_TO_UPDATE_PASSWORD,
  API_TO_SAVE_POST,
  API_TO_FETCH_ALL_POSTS,
  API_TO_SEARCH_USERS,
  API_TO_FETCH_PROFILE_DETAILS,
  API_TO_FETCH_USER_DETAILS,
  API_TO_EDIT_PROFILE_PHOTO,
  API_TO_EDIT_PROFILE,
  API_TO_FETCH_POST_DETAILS,
  API_TO_REPORT_POST,
  API_TO_FETCH_POST_REPORTS,
  API_TO_APPROVE_POST_REPORTS,
  API_TO_REJECT_POST_REPORTS,
  API_TO_FETCH_NOTIFICATIONS,
  API_TO_SAVE_COMMENTS,
  API_TO_LIKE_UNLIKE_POST,
  API_TO_FETCH_POST_LIKES,
  API_TO_DELETE_COMMENT,
  API_TO_DELETE_POST,
  API_TO_FOLLOW_USER,
  API_TO_UNFOLLOW_USER,
  API_TO_FETCH_FOLLOWING_USERS,
  API_TO_FETCH_FOLLOWERS
};
