const BASE_SERVER_URL = "http://localhost:4000";

const API_TO_FETCH_COLLEGE_INFO = BASE_SERVER_URL + "/fetchCollegeList";

const API_TO_SIGNUP_USER = BASE_SERVER_URL + "/signupUser";

const API_TO_LOGIN_USER = BASE_SERVER_URL + "/login";

const API_TO_VERIFY_REFRESH_TOKEN = BASE_SERVER_URL + "/refresh";

export {
    API_TO_FETCH_COLLEGE_INFO,
    API_TO_SIGNUP_USER,
    API_TO_LOGIN_USER,
    API_TO_VERIFY_REFRESH_TOKEN
};