const API_TO_FETCH_COLLEGE_INFO = "/fetchCollegeList";

const API_TO_SIGNUP_USER = "/signupUser";

const API_TO_LOGIN_USER = "/login";

const API_TO_RESET_PASSWORD = "/resetPassword";

const API_TO_UPDATE_PASSWORD = "/updatePassword";

const API_TO_VERIFY_REFRESH_TOKEN = "/refresh";

const API_TO_SAVE_POST = "/savePost";
const API_TO_FETCH_ALL_POSTS = "/allPosts";

const API_TO_SEARCH_USERS = "/searchUser";
const API_TO_FETCH_PROFILE_DETAILS = "/profileDetails";

const API_TO_FETCH_USER_DETAILS = "/userDetails";
const API_TO_EDIT_PROFILE_PHOTO = "/editProfilePhoto";
const API_TO_EDIT_PROFILE = "/editProfile";

const API_TO_FETCH_POST_DETAILS = "/postDetails";

const API_TO_LIKE_UNLIKE_POST = "/like/:id";

module.exports = {
  API_TO_FETCH_COLLEGE_INFO,
  API_TO_SIGNUP_USER,
  API_TO_LOGIN_USER,
  API_TO_RESET_PASSWORD,
  API_TO_UPDATE_PASSWORD,
  API_TO_VERIFY_REFRESH_TOKEN,
  API_TO_SAVE_POST,
  API_TO_FETCH_ALL_POSTS,
  API_TO_SEARCH_USERS,
  API_TO_FETCH_PROFILE_DETAILS,
  API_TO_FETCH_USER_DETAILS,
  API_TO_EDIT_PROFILE_PHOTO,
  API_TO_EDIT_PROFILE,
  API_TO_FETCH_POST_DETAILS,
  API_TO_LIKE_UNLIKE_POST,
};
